# Generated by Django 5.0.4 on 2024-05-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doofer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
