# Generated by Django 5.0.4 on 2024-05-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doofer", "0004_alter_note_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
