# Generated by Django 5.0.4 on 2024-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doofer", "0005_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.AlterField(
            model_name="note",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="note",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
