# Generated by Django 5.0.4 on 2024-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doofer", "0007_remove_note_snippet_alter_note_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content_embedding",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="title_embedding",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
